'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('th'); // 'th' or 'en'

    useEffect(() => {
        const savedLang = localStorage.getItem('app-language');
        const validLanguages = ['th', 'en', 'zh', 'ja', 'ko'];
        if (savedLang && validLanguages.includes(savedLang)) {
            setLanguage(savedLang);
        } else {
            setLanguage('th');
        }
    }, []);

    // ✅ Update html lang attribute dynamically
    useEffect(() => {
        const langMap = {
            th: 'th-TH',
            en: 'en-US', // English with AM/PM time format
            zh: 'zh-CN',
            ja: 'ja-JP',
            ko: 'ko-KR',
        };
        document.documentElement.lang = langMap[language] || 'en-US';
    }, [language]);

    const toggleLanguage = (specificLang) => {
        setLanguage((prev) => {
            if (specificLang) {
                localStorage.setItem('app-language', specificLang);
                return specificLang;
            }
            const languages = ['th', 'en', 'zh', 'ja', 'ko'];
            const currentIndex = languages.indexOf(prev);
            const nextLang = languages[(currentIndex + 1) % languages.length];
            localStorage.setItem('app-language', nextLang);
            return nextLang;
        });
    };

    const translations = {
        th: {
            welcome: "ยินดีต้อนรับ",
            systemName: "ระบบบริหารจัดการวิทยาลัย",
            smartAssistant: "ผู้ช่วยอัจฉริยะ",
            typeMessage: "พิมพ์ข้อความ...",
            dashboard: "แดชบอร์ด",
            schedule: "ตารางสอน",
            students: "นักศึกษา",
            teachers: "อาจารย์",
            subjects: "รายวิชา",
            rooms: "ห้องเรียน",
            departments: "แผนกวิชา",
            levels: "ชั้นปี",
            users: "ผู้ใช้งาน",
            logout: "ออกจากระบบ",

            // Dashboard StatCards
            totalStudents: "นักศึกษาทั้งหมด",
            totalTeachers: "อาจารย์ทั้งหมด",
            totalSubjects: "รายวิชาทั้งหมด",
            totalRooms: "ห้องเรียนทั้งหมด",
            unitPerson: "คน",
            unitSubject: "วิชา",
            unitRoom: "ห้อง",
            statStudents: "นักศึกษา",
            statTeachers: "อาจารย์",
            statUsers: "ผู้ใช้งาน",
            statLevels: "ระดับชั้น",
            statSubjects: "รายวิชา",
            statDepartments: "แผนกวิชา",
            statRooms: "ห้องเรียน",
            statCredits: "หน่วยกิตรวม",
            statCurriculum: "หลักสูตร",
            statSchedule: "ตารางสอน",
            statScheduledSubjects: "วิชาที่จัดตาราง",
            statHours: "ชั่วโมงสอนรวม",
            unitTeacher: "คน",
            unitLevel: "ชั้น",
            unitDept: "แผนก",
            unitCredit: "หน่วย",
            unitItem: "รายการ",
            unitPeriod: "คาบ",
            unitHour: "ชั่วโมง",

            // Chat Widget
            chatHeader: "ผู้ช่วยอัจฉริยะ (AI)",
            chatWelcome: "สวัสดีครับ! ผมคือผู้ช่วย AI 🤖\nมีอะไรให้ผมช่วยเกี่ยวกับการจัดตารางสอนหรือข้อมูลวิทยาลัยไหมครับ?",
            chatError: "ขออภัย ระบบขัดข้อง",
            askSchedule: "ถามเรื่องตารางสอน...",
            poweredBy: "Powered by Ollama AI (ฟรี)",
            chatProcessError: "เกิดข้อผิดพลาดในการประมวลผล",

            // Profile Page
            profileTitle: "ข้อมูลส่วนตัว",
            profileDesc: "จัดการบัญชีและรหัสผ่านของคุณ",
            changePhoto: "เปลี่ยนรูป",
            newPassword: "รหัสผ่านใหม่",
            saveChanges: "บันทึกการเปลี่ยนแปลง",
            processing: "กำลังประมวลผล...",
            fileTooLarge: "ไฟล์ใหญ่เกินไป",
            fileSizeError: "กรุณาเลือกรูปภาพที่มีขนาดไม่เกิน 200KB",
            saveProfileSuccess: "บันทึกสำเร็จ",
            profileUpdated: "ข้อมูลส่วนตัวถูกอัปเดตเรียบร้อยแล้ว",
            saveProfileFailed: "บันทึกไม่สำเร็จ",
            saveProfileError: "เกิดข้อผิดพลาดในการบันทึก",

            // Dynamic Page (Forms)
            editData: "แก้ไขข้อมูล",
            saveData: "บันทึกข้อมูล",
            saving: "กำลังบันทึก...",
            clearForm: "ล้างค่า",
            confirmClear: "ล้างข้อมูลในแบบฟอร์มทั้งหมด?",

            // Form Fields
            studentId: "รหัสนักศึกษา",
            studentIdPlaceholder: "เช่น 66302001001",
            name: "ชื่อที่แสดงผล",
            namePlaceholder: "เช่น นายสมชาย",
            birthdate: "วันเกิด",
            deptName: "แผนกวิชา",
            selectDept: "-- เลือกแผนกวิชา --",
            classLevel: "ชั้นปี",
            selectLevel: "-- เลือกชั้นปี --",
            password: "รหัสผ่าน",
            passwordPlaceholder: "เว้นว่างเพื่อใช้รหัสเดิม",
            teacherId: "รหัสประจำตัวครู",
            teacherIdPlaceholder: "ตัวเลข 8-10 หลัก",
            teacherRoom: "ห้องพักครู",
            teacherRoomPlaceholder: "เช่น ห้องพักครู 1",
            maxHoursLabel: "สอนสูงสุด/สัปดาห์ (คาบ)",
            subjectCode: "รหัสวิชา",
            subjectCodePlaceholder: "เช่น 3000-1201",
            subjectName: "ชื่อวิชา",
            subjectNamePlaceholder: "เช่น คณิตศาสตร์พื้นฐาน",
            credit: "หน่วยกิต",
            theoryHours: "ทฤษฎี (ชม.)",
            practiceHours: "ปฏิบัติ (ชม.)",
            roomName: "ชื่อห้อง / หมายเลขห้อง",
            roomNamePlaceholder: "เช่น 3201, Lab คอมฯ 1",
            roomType: "ประเภทห้อง",
            roomCapacity: "ความจุ (ที่นั่ง)",
            deptNamePlaceholder: "เช่น แผนกวิชาเทคโนโลยีสารสนเทศ",
            usernameLabel: "ชื่อผู้ใช้งาน",
            usernamePlaceholder: "เช่น admin01",
            addUserTitle: "จัดการผู้ใช้งาน",
            addUserDesc: "เพิ่ม/ลบ/แก้ไข บัญชีผู้ดูแลระบบ",

            // Titles & Descs
            addStudentTitle: "เพิ่มนักศึกษาใหม่",
            addStudentDesc: "จัดการข้อมูลนักศึกษาในระบบ",
            addTeacherTitle: "เพิ่มข้อมูลครู",
            addTeacherDesc: "จัดการข้อมูลบุคลากรในระบบ",
            addSubjectTitle: "เพิ่มรายวิชา",
            addSubjectDesc: "กำหนดวิชาและครูผู้สอน",
            addRoomTitle: "เพิ่มห้องเรียน",
            addRoomDesc: "กำหนดห้องเรียน ขนาด และประเภท",
            addDeptTitle: "เพิ่มแผนกวิชา",
            addDeptDesc: "เพิ่ม/ลบ แผนกวิชา",
            scheduleTitle: "จัดตารางสอน",
            curriculum: "กำหนดรายวิชาเรียน",
            menuNotFound: "ไม่พบเมนูนี้",
            pageNotActive: "หน้านี้ยังไม่เปิดใช้งาน",

            // Messages
            saveSuccess: "บันทึกข้อมูลสำเร็จ",
            updateSuccess: "อัปเดตข้อมูลสำเร็จ",
            duplicateFound: "พบข้อมูลซ้ำ",
            duplicateConfirm: "ต้องการบันทึกทับหรือไม่?",
            overwrite: "บันทึกทับ",
            error: "ข้อผิดพลาด",
            connectionError: "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้",
            confirm: "ตกลง",
            cancel: "ยกเลิก",
            all: "ทั้งหมด",
            filterAll: "{label}ทั้งหมด",
            theory: "ทฤษฎี",
            practice: "ปฏิบัติ",
            subject: "วิชา",
            select: "เลือก",
            autoGenBtn: "จัดตารางอัตโนมัติ",
            clearTableBtn: "ล้างตาราง",
            printBtn: "พิมพ์",
            exportExcel: "ส่งออก Excel",
            deleteSelectedBtn: "ลบที่เลือก",
            emptyStateTitle: "ไม่มีข้อมูลตารางสอน",
            emptyStateDesc: "กรุณาเลือกแผนกวิชาและชั้นปีเพื่อดูตารางสอน",
            autoGenTitle: "ยืนยันการจัดตาราง",
            autoGenMessage: "ระบบจะทำการจัดตารางสอนใหม่ทั้งหมด ข้อมูลเดิมอาจถูกเปลี่ยนแปลง",
            autoGenConfirm: "เริ่มจัดตาราง",
            autoGenSkipped: "ข้าม (ไม่มีข้อมูล)",
            autoGenSuccess: "สำเร็จ",
            autoGenFail: "ล้มเหลว",
            manualAddTitle: "เพิ่มรายวิชา (กำหนดเอง)",
            timeDay: "เวลา / วัน",
            monday: "วันจันทร์",
            tuesday: "วันอังคาร",
            wednesday: "วันพุธ",
            thursday: "วันพฤหัสบดี",
            friday: "วันศุกร์",
            saturday: "วันเสาร์",
            sunday: "วันอาทิตย์",
            monday: "วันจันทร์",
            tuesday: "วันอังคาร",
            wednesday: "วันพุธ",
            thursday: "วันพฤหัสบดี",
            friday: "วันศุกร์",
            saturday: "วันเสาร์",
            sunday: "วันอาทิตย์",
            lunchBreak: "พักกลางวัน",
            mySchedule: "ตารางเรียนของฉัน",
            activity: "กิจกรรม",
            lunch: "พัก",
            flagCeremony: "กิจกรรมหน้าเสาธง",
            period: "คาบ",
            scheduleSubtitle: "ดูตารางเรียนประจำภาคเรียน",
            manageScheduleSubtitle: "สร้างและจัดการตารางสอนประจำภาคเรียน",
            termLabel: "ภาคเรียนที่:",

            // AI Clean Data
            cleanData: "ล้างข้อมูล (AI)",
            cleanDataConfirm: "ยืนยันการล้างข้อมูล",
            cleanDataDesc: "AI จะทำการจัดรูปแบบชื่อ (ลบคำนำหน้า) และแก้ไขการเว้นวรรค อาจใช้เวลาสักครู่",
            startCleanup: "เริ่มการล้างข้อมูล",
            aiProcessing: "AI กำลังล้างข้อมูล...",
            cleanupComplete: "ล้างข้อมูลเสร็จสิ้น",
            saveChangesQuery: "AI ได้ล้างข้อมูล {count} รายการ คุณต้องการบันทึกข้อมูลลงฐานข้อมูลหรือไม่?",
            reviewOnly: "ดูตัวอย่างเท่านั้น",
            noDataToClean: "ไม่มีข้อมูลให้ล้าง",

            // DatePicker
            // DatePicker
            dateDay: "วัน",
            dateMonth: "เดือน",
            dateYear: "ปี",

            // Schedule Page
            term: "ภาคเรียน",
            department: "แผนกวิชา",
            select: "เลือก",
            filterBtn: "ค้นหา",
            addSubjectBtn: "เพิ่มรายวิชา",
            autoGenBtn: "จัดตารางอัตโนมัติ",
            clearTableBtn: "ล้างตาราง",
            deleteSelectedBtn: "ลบที่เลือก",
            printBtn: "พิมพ์ตาราง",
            emptyStateTitle: "ยังไม่มีข้อมูลตารางสอน",
            emptyStateDesc: "กรุณาเลือก แผนกวิชา และ ชั้นปี เพื่อดูตารางสอน",
            timeDay: "เวลา / วัน",
            monday: "วันจันทร์",
            tuesday: "วันอังคาร",
            wednesday: "วันพุธ",
            thursday: "วันพฤหัสบดี",
            friday: "วันศุกร์",
            saturday: "วันเสาร์",
            sunday: "วันอาทิตย์",
            lunchBreak: "พักกลางวัน",
            manualAddTitle: "เพิ่มรายวิชาลงตาราง (Manual)",
            day: "วัน",
            subject: "วิชา",
            teacher: "ครูผู้สอน",
            room: "ห้องเรียน",
            startTime: "คาบเริ่มต้น",
            duration: "จำนวนคาบ",
            hours: "ชั่วโมง",
            addToTableBtn: "เพิ่มลงตาราง",
            clearTableTitle: "ล้างข้อมูลตารางสอน",
            clearMode: "โหมดการล้าง",
            clearAll: "ล้างทั้งหมด (ทุกชั้นปี)",
            clearCurrent: "ล้างเฉพาะชั้นปีนี้",
            autoGenTitle: "ยืนยันการจัดตารางอัตโนมัติ",
            autoGenMessage: "ระบบจะทำการจัดตารางสอนให้กับ **ทุกชั้นปี** ในแผนกที่เลือก \nข้อมูลเดิมจะถูกลบและแทนที่ด้วยตารางใหม่จาก AI",
            autoGenConfirm: "เริ่มจัดตาราง (Batch)",
            autoGenSuccess: "จัดตารางสำเร็จ",
            autoGenFail: "จัดตารางล้มเหลว",
            autoGenSkipped: "ข้าม (ไม่มีข้อมูลหลักสูตร)",
            success: "สำเร็จ",
            noData: "ไม่มีข้อมูล",

            // Levels Page
            addLevelTitle: "เพิ่มระดับชั้น",
            addLevelDesc: "เพิ่ม/ลบ ระดับชั้นเรียน",
            levelName: "ชื่อระดับชั้น",
            levelNamePlaceholder: "เช่น ปวช. 1/1",
            levelSaveSuccess: "เพิ่มระดับชั้นเรียบร้อยแล้ว",

            // Curriculum Page
            curriculumTitle: "กำหนดรายวิชาเรียน",
            curriculumDesc: "เลือกรายวิชาตามหลักสูตรสำหรับระดับชั้นและแผนกวิชาที่เลือก",
            allSubjects: "รายวิชาทั้งหมด",
            selectSubjectsDesc: "เลือกวิชาที่ต้องการสอนในชั้นปีนี้",
            askAI: "ให้ AI แนะนำ",
            selectedCount: "เลือกแล้ว",
            aiRecommended: "AI แนะนำ",
            noSubjectsFound: "ไม่พบรายวิชาสำหรับแผนกนี้",
            selectLevelDeptFirst: "กรุณาเลือกระดับชั้นและแผนกวิชาเพื่อเริ่มต้น",
            aiRecommendSuccess: "AI แนะนำสำเร็จ",
            aiRecommendMessage: "AI ได้แนะนำรายวิชาที่เหมาะสม",
            aiRecommendError: "AI ไม่สามารถแนะนำได้ในขณะนี้",
            clearSelection: "ล้างค่าที่เลือก",

            // TableModal
            manualAddTitle: 'เพิ่มรายวิชา (Manual)',
            editTitle: 'แก้ไขรายวิชา',
            day: 'วันเรียน',
            subject: 'วิชา',
            room: 'ห้องเรียน',
            startPeriod: 'เริ่มคาบที่',
            duration: 'จำนวนคาบ',
            cancel: 'ยกเลิก',
            save: 'บันทึก',
            confirm: 'ยืนยัน',
            delete: 'ลบ',
            warning: 'คำเตือน',
            success: 'สำเร็จ',
            error: 'ข้อผิดพลาด',
            noData: 'ไม่พบข้อมูล',
            students: 'นักเรียน',
            teacher: 'ครูผู้สอน',
            classLevel: 'ชั้นปี',
            department: 'แผนกวิชา',
            users: 'ผู้ใช้งาน',
            duplicateMsg: 'ข้อมูลซ้ำ: "{value}"\nต้องการทับข้อมูลเดิมหรือไม่?',
            errorMsg: 'เกิดข้อผิดพลาด: {error}',
            excelEmpty: 'ไฟล์ Excel ไม่มีข้อมูล',
            foundItems: 'พบข้อมูล {count} รายการ\nเริ่มนำเข้าข้อมูล?',
            invalidExcel: 'ไฟล์ Excel ไม่ถูกต้อง',
            failedDelete: 'ลบข้อมูลไม่สำเร็จ',
            deleteWarning: 'ข้อมูลจะถูกลบถาวร',
            recoverWarning: 'ข้อมูลไม่สามารถกู้คืนได้',
            templateDownloaded: 'ดาวน์โหลดเทมเพลตเรียบร้อยแล้ว',
            manageData: 'จัดการข้อมูล {title} ในระบบ',
            templateBtn: 'เทมเพลต',
            importBtn: 'นำเข้า Excel',
            searchPlaceholder: 'ค้นหา...',
            showing: 'แสดง {start} - {end} จาก {total}',
            birthdate: 'วันเกิด',
            maxHours: 'ชั่วโมงสอนสูงสุด',
            credit: 'หน่วยกิต',
            theory: 'ทฤษฎี',
            practice: 'ปฏิบัติ',
            type: 'ประเภท',
            capacity: 'ความจุ',
            username: 'ชื่อผู้ใช้',
            fullname: 'ชื่อ-นามสกุล',
            role: 'สิทธิ์การใช้งาน',
            studentCount: 'จำนวนนักเรียน',
            totalHours: 'รวมชั่วโมง',
            time: 'เวลา',
            action: 'จัดการ',
            item: 'รายการ',
            seq: 'ลำดับ',
            orderIndex: 'ลำดับ',
            agentPlanning: 'วิเคราะห์เงื่อนไข',
            agentReasoning: 'วางแผนจัดตาราง',
            agentAction: 'ลงตารางสอน',
            agentReview: 'ตรวจสอบความถูกต้อง',

            // Login Page
            loginTitle: 'เข้าสู่ระบบ',
            loginSubtitle: 'ระบบบริหารจัดการวิทยาลัย',
            usernameLogin: 'ชื่อผู้ใช้งาน',
            passwordLogin: 'รหัสผ่าน',
            loginButton: 'เข้าสู่ระบบ',
            loggingIn: 'กำลังเข้าสู่ระบบ...',
            loginSuccess: 'เข้าสู่ระบบสำเร็จ',
            loginWelcome: 'ยินดีต้อนรับเข้าสู่ระบบ',
            loginFailed: 'เข้าสู่ระบบไม่สำเร็จ',
            loginError: 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
            tryAgain: 'ลองใหม่',
            ok: 'ตกลง',
            copyright: '© 2025 วิทยาลัยเทคนิคสุพรรณบุรี',

            // Header
            adminRole: 'ผู้ดูแลระบบ',
            profile: 'ข้อมูลส่วนตัว',

            // Tooltips
            mute: 'ปิดเสียง',
            unmute: 'เปิดเสียง',
            voiceOn: 'สั่งงานด้วยเสียง',
            voiceOff: 'ปิดสั่งงานเสียง',
            handOn: 'ควบคุมด้วยมือ',
            handOff: 'ปิดการควบคุมมือ',

            // Sidebar New Keys
            attendance: 'เช็คชื่อ',
            aiComparison: 'เปรียบเทียบ AI',
            issueReports: 'รายการแจ้งปัญหา',
            reportIssue: 'แจ้งปัญหา',
            settings: 'ตั้งค่า',
            help: 'ช่วยเหลือ',
            viewData: 'ดูข้อมูล',
            addEdit: 'เพิ่ม/แก้ไข',
            importExcel: 'นำเข้า Excel',

            // Dashboard New Keys
            roomUtilization: 'อัตราใช้ห้อง',
            teachingLoad: 'ภาระงานครู',
            teacherDaily: 'ชั่วโมงสอนวันนี้',
            teacherWeekly: 'ชั่วโมงสอนสัปดาห์นี้',
            teacherTerm: 'ชั่วโมงสอนภาคเรียนนี้',
            teacherSubjects: 'รายวิชาที่รับผิดชอบ',
            studentClassesToday: 'คาบเรียนวันนี้',
            studentClassesWeek: 'คาบเรียนสัปดาห์นี้',
            studentAttendance: 'อัตราเข้าเรียน',
            studentSubjects: 'รายวิชาที่ลงทะเบียน',
            clickToViewGraph: 'คลิกเพื่อดูกราฟ',
            loadSampleDataTitle: '🚀 เริ่มต้นใช้งานระบบ',
            loadSampleDataDesc: 'โหลดข้อมูลตัวอย่าง (3 แผนก, 10 ครู, 50 นักเรียน, 15 วิชา) เพื่อทดลองใช้งานระบบ',
            loadSampleDataBtn: 'โหลดข้อมูลตัวอย่าง',
            loadingSample: 'กำลังโหลด...',

            // Report
            reportTitle: 'แจ้งปัญหา / ข้อเสนอแนะ',
            reportDesc: 'แจ้งปัญหาการใช้งานหรือเสนอแนะเพิ่มเติม',
            typeBug: 'แจ้งปัญหา (Bug)',
            typeFeature: 'เสนอแนะ (Feature)',
            typeQuestion: 'สอบถาม (Question)',
            alertFillRequired: 'กรุณากรอกหัวข้อและรายละเอียด',
            sentSuccess: 'ส่งรายงานเรียบร้อยแล้ว!',
            reportId: 'รหัสรายงาน',
            newReport: 'ส่งรายงานใหม่',
            typeLabel: 'ประเภท',
            topicLabel: 'หัวข้อ',
            topicPlaceholder: 'สรุปสั้นๆ (เช่น เข้าสู่ระบบไม่ได้)',
            detailLabel: 'รายละเอียด',
            detailPlaceholder: 'อธิบายปัญหาที่พบ หรือสิ่งที่ต้องการเสนอแนะ...',
            sendReportBtn: 'ส่งรายงาน',

            // Settings
            settingsTitle: 'ตั้งค่า Dashboard',
            settingsDesc: 'ปรับแต่งการแสดงผลตามต้องการ',
            resetConfig: 'รีเซ็ตการตั้งค่าทั้งหมด?',
            resetBtn: 'รีเซ็ต',
            saved: 'บันทึกแล้ว!',
            // Shapes
            shapeRounded: 'มุมมน',
            shapePill: 'แคปซูล',
            shapeSharp: 'มุมเหลี่ยม',
            shapeSoft: 'มุมนุ่ม',
            // Styles
            styleGradient: 'ไล่สี',
            styleSolid: 'สีเดียว',
            styleGlass: 'กระจก',
            styleOutline: 'เส้นขอบ',
            // Colors
            colorBlue: 'น้ำเงิน',
            colorEmerald: 'เขียว',
            colorViolet: 'ม่วง',
            colorAmber: 'เหลือง',
            colorRose: 'ชมพู',
            colorCyan: 'ฟ้า',
            colorOrange: 'ส้ม',
            colorPink: 'ชมพูอ่อน',
            colorRed: 'แดง',
            colorIndigo: 'คราม',
            colorTeal: 'เทา',
            colorLime: 'เขียวอ่อน',
        },
        en: {
            welcome: "Welcome",
            systemName: "College Management System",
            smartAssistant: "Smart Assistant",
            typeMessage: "Type a message...",
            dashboard: "Dashboard",
            schedule: "Schedule",
            students: "Students",
            teachers: "Teachers",
            subjects: "Subjects",
            rooms: "Rooms",

            // Tooltips
            mute: 'Mute',
            unmute: 'Unmute',
            voiceOn: 'Voice Control On',
            voiceOff: 'Voice Control Off',
            handOn: 'Hand Control On',
            handOff: 'Hand Control Off',

            // Header
            adminRole: 'Administrator',
            profile: 'Profile',

            // Report
            reportTitle: 'Report Issue / Feedback',
            reportDesc: 'Report bugs or send feedback',
            typeBug: 'Bug Report',
            typeFeature: 'Feature Request',
            typeQuestion: 'General Question',
            alertFillRequired: 'Please fill in title and description',
            sentSuccess: 'Report Sent Successfully!',
            reportId: 'Report ID',
            newReport: 'Send New Report',
            typeLabel: 'Type',
            topicLabel: 'Topic',
            topicPlaceholder: 'Brief summary (e.g. Cannot login)',
            detailLabel: 'Description',
            detailPlaceholder: 'Describe the issue or feedback...',
            sendReportBtn: 'Send Report',

            // Settings
            settingsTitle: 'Dashboard Settings',
            settingsDesc: 'Customize your dashboard view',
            resetConfig: 'Reset all settings?',
            resetBtn: 'Reset',
            saved: 'Saved!',

            // Shapes
            shapeRounded: 'Rounded',
            shapePill: 'Pill',
            shapeSharp: 'Sharp',
            shapeSoft: 'Soft',
            // Styles
            styleGradient: 'Gradient',
            styleSolid: 'Solid',
            styleGlass: 'Glass',
            styleOutline: 'Outline',
            // Colors
            colorBlue: 'Blue',
            colorEmerald: 'Emerald',
            colorViolet: 'Violet',
            colorAmber: 'Amber',
            colorRose: 'Rose',
            colorCyan: 'Cyan',
            colorOrange: 'Orange',
            colorPink: 'Pink',
            colorRed: 'Red',
            colorIndigo: 'Indigo',
            colorTeal: 'Teal',
            colorLime: 'Lime',
            departments: "Departments",
            users: "Users",
            logout: "Logout",

            // Dashboard StatCards
            totalStudents: "Total Students",
            totalTeachers: "Total Teachers",
            totalSubjects: "Total Subjects",
            totalRooms: "Total Rooms",
            unitPerson: "Persons",
            unitSubject: "Subjects",
            unitRoom: "Rooms",
            statStudents: "Students",
            statTeachers: "Teachers",
            statUsers: "Users",
            statLevels: "Levels",
            statSubjects: "Subjects",
            statDepartments: "Departments",
            statRooms: "Rooms",
            statCredits: "Total Credits",
            statCurriculum: "Curriculum",
            statSchedule: "Schedule",
            statScheduledSubjects: "Scheduled",
            statHours: "Total Hours",
            unitTeacher: "Persons",
            unitLevel: "Levels",
            unitDept: "Depts",
            unitCredit: "Credits",
            unitItem: "Items",
            unitPeriod: "Periods",
            unitHour: "Hours",

            // Chat Widget
            chatHeader: "Smart Assistant (AI)",
            chatWelcome: "Hello! I'm your AI Assistant 🤖\nHow can I help you with scheduling or college data?",
            chatError: "Sorry, system error.",
            askSchedule: "Ask about schedule...",
            poweredBy: "Powered by Ollama AI (ฟรี)",
            chatProcessError: "Processing error occurred",

            // Profile Page
            profileTitle: "Profile",
            profileDesc: "Manage your account and password",
            changePhoto: "Change Photo",
            newPassword: "New Password",
            saveChanges: "Save Changes",
            processing: "Processing...",
            fileTooLarge: "File too large",
            fileSizeError: "Please select an image under 200KB",
            saveProfileSuccess: "Saved Successfully",
            profileUpdated: "Profile updated successfully",
            saveProfileFailed: "Save Failed",
            saveProfileError: "Error saving data",

            // Dynamic Page (Forms)
            editData: "Edit Data",
            saveData: "Save Data",
            saving: "Saving...",
            clearForm: "Clear Form",
            confirmClear: "Clear all form data?",

            // Form Fields
            studentId: "Student ID",
            studentIdPlaceholder: "e.g. 66302001001",
            name: "Display Name",
            namePlaceholder: "e.g. John Doe",
            birthdate: "Birthdate",
            deptName: "Department",
            selectDept: "-- Select Department --",
            classLevel: "Class Level",
            selectLevel: "-- Select Level --",
            // New language entries

            password: "Password",
            passwordPlaceholder: "Leave blank to keep original",
            teacherId: "Teacher ID",
            teacherIdPlaceholder: "8-10 digits",
            teacherRoom: "Teacher Room",
            teacherRoomPlaceholder: "e.g. Room 1",
            maxHoursLabel: "Max Hours/Week",
            subjectCode: "Subject Code",
            subjectCodePlaceholder: "e.g. 3000-1201",
            subjectName: "Subject Name",
            subjectNamePlaceholder: "e.g. Basic Math",
            credit: "Credit",
            theoryHours: "Theory (Hrs)",
            practiceHours: "Practice (Hrs)",
            roomName: "Room Name / Number",
            roomNamePlaceholder: "e.g. 3201, Computer Lab 1",
            roomType: "Room Type",
            roomCapacity: "Capacity (Seats)",
            deptNamePlaceholder: "e.g. Information Technology",
            usernameLabel: "Username",
            usernamePlaceholder: "e.g. admin01",
            addUserTitle: "Manage Users",
            addUserDesc: "Add/Edit/Delete Admin Accounts",

            // Titles & Descs
            addStudentTitle: "Add New Student",
            addStudentDesc: "Manage student data in the system",
            addTeacherTitle: "Add Teacher Data",
            addTeacherDesc: "Manage personnel data in the system",
            addSubjectTitle: "Add Subject",
            addSubjectDesc: "Define subjects and instructors",
            addRoomTitle: "Add Room",
            addRoomDesc: "Define room type and capacity",
            addDeptTitle: "Add Department",
            addDeptDesc: "Add/Remove Departments",
            scheduleTitle: "Manage Schedule",
            curriculum: "Curriculum Settings",
            menuNotFound: "Menu Not Found",
            pageNotActive: "Page Not Active",

            // Messages
            saveSuccess: "Saved Successfully",
            updateSuccess: "Updated Successfully",
            duplicateFound: "Duplicate Data Found",
            duplicateConfirm: "Do you want to overwrite?",
            overwrite: "Overwrite",
            error: "Error",
            connectionError: "Cannot connect to server",
            confirm: "Confirm",
            cancel: "Cancel",
            all: "All",
            filterAll: "All {label}",
            theory: "Theory",
            practice: "Practice",
            subject: "Subject",
            select: "Select",
            autoGenBtn: "Auto Schedule",
            clearTableBtn: "Clear Table",
            printBtn: "Print",
            exportExcel: "Export Excel",
            deleteSelectedBtn: "Delete Selected",
            emptyStateTitle: "No Schedule Data",
            emptyStateDesc: "Please select Department and Class Level to view schedule",
            autoGenTitle: "Confirm Auto Schedule",
            autoGenMessage: "The system will regenerate the schedule. Existing data may be changed.",
            autoGenConfirm: "Start Scheduling",
            autoGenSkipped: "Skipped (No Data)",
            autoGenSuccess: "Success",
            autoGenFail: "Failed",
            manualAddTitle: "Add Subject (Manual)",
            timeDay: "Time / Day",
            monday: "Monday",
            tuesday: "Tuesday",
            wednesday: "Wednesday",
            thursday: "Thursday",
            friday: "Friday",
            saturday: "Saturday",
            sunday: "Sunday",
            monday: "Monday",
            tuesday: "Tuesday",
            wednesday: "Wednesday",
            thursday: "Thursday",
            friday: "Friday",
            saturday: "Saturday",
            sunday: "Sunday",
            lunchBreak: "Lunch Break",
            mySchedule: "My Schedule",
            activity: "Activity",
            lunch: "Lunch",
            flagCeremony: "Flag Ceremony",
            period: "Period",
            scheduleSubtitle: "View your class schedule for this semester",
            manageScheduleSubtitle: "Create and manage class schedules",
            termLabel: "Semester:",

            // AI Clean Data
            cleanData: "Clean Data (AI)",
            cleanDataConfirm: "Confirm Data Cleanup",
            cleanDataDesc: "AI will format names (remove prefixes) and fix spacing. This may take a few seconds.",
            startCleanup: "Start Cleanup",
            aiProcessing: "AI is cleaning your data...",
            cleanupComplete: "Cleanup Complete",
            saveChangesQuery: "AI cleaned {count} items. Do you want to save these changes to the database?",
            reviewOnly: "Review Only",
            noDataToClean: "No data to clean",

            // DatePicker
            // DatePicker
            dateDay: "Day",
            dateMonth: "Month",
            dateYear: "Year",

            // Schedule Page
            term: "Term",
            department: "Department",
            select: "Select",
            filterBtn: "Search",
            addSubjectBtn: "Add Subject",
            autoGenBtn: "Auto Schedule",
            clearTableBtn: "Clear Table",
            deleteSelectedBtn: "Delete Selected",
            printBtn: "Print",
            emptyStateTitle: "No Schedule Data",
            emptyStateDesc: "Please select Department and Class Level to view schedule",
            timeDay: "Time / Day",
            monday: "Monday",
            tuesday: "Tuesday",
            wednesday: "Wednesday",
            thursday: "Thursday",
            friday: "Friday",
            saturday: "Saturday",
            sunday: "Sunday",
            lunchBreak: "Lunch Break",
            manualAddTitle: "Manual Add Subject",
            day: "Day",
            subject: "Subject",
            teacher: "Teacher",
            room: "Room",
            startTime: "Start Period",
            duration: "Duration",
            hours: "Hours",
            addToTableBtn: "Add to Table",
            clearTableTitle: "Clear Schedule Data",
            clearMode: "Clear Mode",
            clearAll: "Clear All (All Levels)",
            clearCurrent: "Clear Current Level Only",
            autoGenTitle: "Confirm Auto Schedule",
            autoGenMessage: "System will generate schedule for **ALL Levels** in selected department.\nExisting data will be replaced by AI.",
            autoGenConfirm: "Start Batch Process",
            autoGenSuccess: "Success",
            autoGenFail: "Failed",
            autoGenSkipped: "Skipped (No Curriculum)",
            success: "Success",
            noData: "No Data",

            // Levels Page
            addLevelTitle: "Add Class Level",
            addLevelDesc: "Add/Remove Class Levels",
            levelName: "Level Name",
            levelNamePlaceholder: "e.g. Voc. 1/1",
            levelSaveSuccess: "Class level added successfully",

            // Curriculum Page
            curriculumTitle: "Curriculum Settings",
            curriculumDesc: "Select subjects for the chosen level and department",
            allSubjects: "All Subjects",
            selectSubjectsDesc: "Select subjects to teach for this level",
            askAI: "Ask AI",
            selectedCount: "Selected",
            aiRecommended: "AI Recommended",
            noSubjectsFound: "No subjects found for this department",
            selectLevelDeptFirst: "Please select Level and Department to start",
            aiRecommendSuccess: "AI Recommendation Success",
            aiRecommendMessage: "AI has recommended suitable subjects",
            aiRecommendError: "AI cannot recommend at this time",
            clearSelection: "Clear Selection",

            // TableModal
            manualAddTitle: 'Add Subject (Manual)',
            editTitle: 'Edit Data',
            day: 'Day',
            subject: 'Subject',
            room: 'Room',
            startPeriod: 'Start Period',
            duration: 'Duration',
            cancel: 'Cancel',
            save: 'Save',
            confirm: 'Confirm',
            delete: 'Delete',
            warning: 'Warning',
            success: 'Success',
            error: 'Error',
            noData: 'No Data',
            students: 'Students',
            teacher: 'Teacher',
            classLevel: 'Class Level',
            department: 'Department',
            users: 'Users',
            duplicateMsg: 'Duplicate: "{value}"\nOverwrite?',
            errorMsg: 'Error: {error}',
            excelEmpty: 'Excel file is empty',
            foundItems: 'Found {count} items.\nStart import?',
            invalidExcel: 'Invalid Excel file',
            failedDelete: 'Failed to delete',
            deleteWarning: 'Data will be permanently deleted',
            recoverWarning: 'Data cannot be recovered',
            templateDownloaded: 'Template downloaded',
            manageData: 'Manage {title} data in database',
            templateBtn: 'Template',
            importBtn: 'Import Excel',
            searchPlaceholder: 'Search...',
            showing: 'Showing {start} - {end} of {total}',
            birthdate: 'Birthdate',
            maxHours: 'Max Hours',
            credit: 'Credit',
            theory: 'Theory',
            practice: 'Practice',
            type: 'Type',
            capacity: 'Capacity',
            username: 'Username',
            fullname: 'Fullname',
            role: 'Role',
            studentCount: 'Student Count',
            totalHours: 'Total Hours',
            time: 'Time',
            action: 'Action',
            item: 'Item',
            seq: 'No.',
            orderIndex: 'No.',
            agentPlanning: 'Analyzing Constraints',
            agentReasoning: 'Designing Strategy',
            agentAction: 'Assigning Schedule',
            agentReview: 'Verifying Conflicts',

            // Login Page
            loginTitle: 'Login',
            loginSubtitle: 'College Management System',
            usernameLogin: 'Username',
            passwordLogin: 'Password',
            loginButton: 'Login',
            loggingIn: 'Logging in...',
            loginSuccess: 'Login Successful',
            loginWelcome: 'Welcome to the system',
            loginFailed: 'Login Failed',
            loginError: 'Invalid username or password',
            tryAgain: 'Try Again',
            ok: 'OK',
            copyright: '© 2025 Suphanburi Technical College',

            // Header
            adminRole: 'Administrator',
            profile: 'Profile',

            // Sidebar New Keys
            attendance: 'Attendance',
            aiComparison: 'AI Comparison',
            issueReports: 'Issue Reports',
            reportIssue: 'Report Issue',
            settings: 'Settings',
            help: 'Help',
            viewData: 'View Data',
            addEdit: 'Add/Edit',
            importExcel: 'Import Excel',

            // Dashboard New Keys
            roomUtilization: 'Room Utilization',
            teachingLoad: 'Teaching Load',
            teacherDaily: 'Daily Hours',
            teacherWeekly: 'Weekly Hours',
            teacherTerm: 'Term Hours',
            teacherSubjects: 'My Subjects',
            studentClassesToday: 'Classes Today',
            studentClassesWeek: 'Classes Weekly',
            studentAttendance: 'Attendance Rate',
            studentSubjects: 'Enrolled Subjects',
            clickToViewGraph: 'Click to view graph',
            loadSampleDataTitle: '🚀 Get Started',
            loadSampleDataDesc: 'Load sample data (3 Depts, 10 Teachers, 50 Students, 15 Subjects) to test the system',
            loadSampleDataBtn: 'Load Sample Data',
            loadingSample: 'Loading...',
        },
        zh: {
            welcome: "欢迎",
            systemName: "学院管理系统",
            dashboard: "仪表板",
            schedule: "课程表",
            students: "学生",
            teachers: "教师",
            subjects: "科目",
            rooms: "教室",
            departments: "院系",
            levels: "年级",
            curriculum: "课程设置",
            users: "用户",
            logout: "登出",
            save: "保存",
            cancel: "取消",
            all: "全部",
            filterAll: "全部 {label}",
            theory: "理论",
            practice: "实践",
            subject: "科目",
            select: "选择",
            autoGenBtn: "自动排课",
            clearTableBtn: "清空课表",
            printBtn: "打印",
            deleteSelectedBtn: "删除所选",
            emptyStateTitle: "无课表数据",
            emptyStateDesc: "请选择院系和年级以查看课表",
            autoGenTitle: "确认自动排课",
            autoGenMessage: "系统将重新生成课表，现有数据可能会更改。",
            autoGenConfirm: "开始排课",
            autoGenSkipped: "跳过 (无数据)",
            autoGenSuccess: "成功",
            autoGenFail: "失败",
            manualAddTitle: "添加科目 (手动)",
            timeDay: "时间 / 星期",
            monday: "星期一",
            tuesday: "星期二",
            wednesday: "星期三",
            thursday: "星期四",
            friday: "星期五",
            saturday: "星期六",
            sunday: "星期日",
            lunchBreak: "午休",

            // AI Clean Data
            cleanData: "清理数据 (AI)",
            cleanDataConfirm: "确认数据清理",
            cleanDataDesc: "AI 将格式化名称（去除前缀）并修复间距。这可能需要几秒钟。",
            startCleanup: "开始清理",
            aiProcessing: "AI 正在清理您的数据...",
            cleanupComplete: "清理完成",
            saveChangesQuery: "AI 清理了 {count} 个项目。您要将这些更改保存到数据库吗？",
            reviewOnly: "仅预览",
            noDataToClean: "没有要清理的数据",

            // DatePicker
            // DatePicker
            dateDay: "日",
            dateMonth: "月",
            dateYear: "年",

            teacher: "教师",
            room: "教室",
            type: "类型",
            capacity: "容量",
            day: "星期",
            period: "节次",
            confirm: "确认",
            delete: "删除",
            edit: "编辑",
            add: "添加",
            search: "搜索",
            clear: "清除",
            clearSelection: "清除选择",
            action: "操作",
            // StatCards
            totalStudents: "学生总数",
            totalTeachers: "教师总数",
            totalSubjects: "科目总数",
            totalRooms: "教室总数",
            unitPerson: "人",
            unitSubject: "科",
            unitRoom: "间",
            statStudents: "学生",
            statTeachers: "教师",
            statUsers: "用户",
            statLevels: "年级",
            statSubjects: "科目",
            statDepartments: "院系",
            statRooms: "教室",
            statCredits: "总学分",
            statCurriculum: "课程",
            statSchedule: "课表",
            statScheduledSubjects: "已排课程",
            statHours: "总课时",
            unitTeacher: "人",
            unitLevel: "个",
            unitDept: "个",
            unitCredit: "分",
            unitItem: "项",
            unitPeriod: "节",
            unitHour: "小时",
            seq: "序号",
            department: "系",
            term: "学期",

            // Chat Widget
            chatHeader: "智能助手 (AI)",
            chatWelcome: "你好！我是你的 AI 助手 🤖\n有什么我可以帮你安排课程表或学院数据的吗？",
            chatError: "抱歉，系统错误",
            askSchedule: "询问课程表...",
            poweredBy: "Powered by Ollama AI (ฟรี)",
            chatProcessError: "处理时发生错误",

            // Profile Page
            profileTitle: "个人资料",
            profileDesc: "管理您的帐户和密码",
            changePhoto: "更换照片",
            newPassword: "新密码",
            saveChanges: "保存更改",
            processing: "处理中...",
            fileTooLarge: "文件过大",
            fileSizeError: "请选择小于 200KB 的图片",
            saveProfileSuccess: "保存成功",
            profileUpdated: "个人资料已更新",
            saveProfileFailed: "保存失败",
            saveProfileError: "保存数据时出错",
            // Forms
            editData: "编辑数据",
            saveData: "保存数据",
            saving: "保存中...",
            clearForm: "清除表单",
            confirmClear: "确认清除所有数据?",
            studentId: "学号",
            name: "显示名称",
            birthdate: "生日",
            deptName: "院系",
            selectDept: "-- 选择院系 --",
            classLevel: "年级",
            selectLevel: "-- 选择年级 --",
            password: "密码",
            teacherId: "教师编号",
            teacherRoom: "教师办公室",
            maxHoursLabel: "每周最大课时",
            subjectCode: "科目编号",
            subjectName: "科目名称",
            credit: "学分",
            theoryHours: "理论课时",
            practiceHours: "实践课时",
            roomName: "教室名称/编号",
            roomType: "教室类型",
            roomCapacity: "容量",
            usernameLabel: "用户名",
            addUserTitle: "管理用户",

            // TableModal
            manageData: "管理数据库中的 {title} 数据",
            addSubjectBtn: "添加项目",
            templateBtn: "模板",
            importBtn: "导入 Excel",
            searchPlaceholder: "搜索...",
            showing: "显示 {start} - {end} 共 {total}",
            deleteWarning: "数据将被永久删除",
            recoverWarning: "数据无法恢复",
            templateDownloaded: "模板已下载",
            excelEmpty: "Excel 文件为空",
            foundItems: "发现 {count} 个项目。\n开始导入？",
            invalidExcel: "无效的 Excel 文件",
            failedDelete: "删除失败",
            duplicateMsg: "重复数据: \"{value}\"\n是否覆盖？",
            errorMsg: "错误: {error}",
            noData: "无数据",
            success: "成功",
            warning: "警告",

            // Placeholders
            namePlaceholder: "例如: 张三",
            studentIdPlaceholder: "例如: 66302001001",
            passwordPlaceholder: "留空保持原密码",
            teacherIdPlaceholder: "8-10位数字",
            teacherRoomPlaceholder: "例如: 教师室1",
            subjectCodePlaceholder: "例如: 3000-1201",
            subjectNamePlaceholder: "例如: 基础数学",
            roomNamePlaceholder: "例如: 3201, 计算机室1",
            deptNamePlaceholder: "例如: 信息技术学院",
            usernamePlaceholder: "例如: admin01",
            levelNamePlaceholder: "例如: 职校1年级/1班",

            // Page Titles & Descriptions
            addStudentTitle: "添加新学生",
            addStudentDesc: "管理系统中的学生数据",
            addTeacherTitle: "添加教师数据",
            addTeacherDesc: "管理系统中的教职员工数据",
            addSubjectTitle: "添加科目",
            addSubjectDesc: "定义科目和教师",
            addRoomTitle: "添加教室",
            addRoomDesc: "定义教室类型和容量",
            addDeptTitle: "添加院系",
            addDeptDesc: "添加/删除院系",
            addLevelTitle: "添加年级",
            addLevelDesc: "添加/删除年级",
            addUserDesc: "添加/编辑/删除管理员账户",
            scheduleTitle: "课表管理",
            menuNotFound: "菜单未找到",
            pageNotActive: "页面未激活",

            // Messages
            saveSuccess: "保存成功",
            updateSuccess: "更新成功",
            duplicateFound: "发现重复数据",
            duplicateConfirm: "要覆盖吗？",
            overwrite: "覆盖",
            error: "错误",
            connectionError: "无法连接服务器",
            levelSaveSuccess: "年级添加成功",

            // Curriculum
            curriculumTitle: "课程设置",
            curriculumDesc: "为选定的年级和院系选择科目",
            allSubjects: "所有科目",
            selectSubjectsDesc: "选择该年级要教授的科目",
            askAI: "询问AI",
            selectedCount: "已选择",
            aiRecommended: "AI推荐",
            noSubjectsFound: "该院系没有科目",
            selectLevelDeptFirst: "请先选择年级和院系",
            aiRecommendSuccess: "AI推荐成功",
            aiRecommendMessage: "AI已推荐合适的科目",
            aiRecommendError: "AI暂时无法推荐",

            // Schedule
            smartAssistant: "智能助手",
            filterBtn: "筛选",
            addSubjectBtn: "添加科目",
            addToTableBtn: "添加到课表",
            clearTableTitle: "清空课表数据",
            clearMode: "清空模式",
            clearAll: "全部清空（所有年级）",
            clearCurrent: "仅清空当前年级",
            hours: "小时",
            startTime: "开始时间",
            startPeriod: "开始节次",
            duration: "持续时间",
            editTitle: "编辑数据",

            // TableModal extras
            maxHours: "最大课时",
            username: "用户名",
            fullname: "全名",
            role: "角色",
            studentCount: "学生人数",
            totalHours: "总课时",
            time: "时间",
            item: "项目",
            agentPlanning: "分析条件",
            agentReasoning: "设计策略",
            agentAction: "分配时间表",
            agentReview: "检查冲突",

            // Login Page
            loginTitle: "登录",
            loginSubtitle: "学院管理系统",
            usernameLogin: "用户名",
            passwordLogin: "密码",
            loginButton: "登录",
            loggingIn: "登录中...",
            loginSuccess: "登录成功",
            loginWelcome: "欢迎进入系统",
            loginFailed: "登录失败",
            loginError: "用户名或密码错误",
            tryAgain: "重试",
            ok: "确定",
            copyright: "© 2025 素攀武里技术学院",

            // Header
            adminRole: "管理员",
            profile: "个人资料",
            typeMessage: "输入消息...",

            // Sidebar New Keys
            attendance: '考勤',
            schedule: '课程表',
            aiComparison: 'AI 对比',
            issueReports: '问题报告',
            reportIssue: '报告问题',
            settings: '设置',
            help: '帮助',
            viewData: '查看数据',
            addEdit: '添加/编辑',
            importExcel: '导入 Excel',

            // Dashboard New Keys
            roomUtilization: '教室利用率',
            teachingLoad: '教学工作量',
            teacherDaily: '今日课时',
            teacherWeekly: '本周课时',
            teacherTerm: '本学期课时',
            teacherSubjects: '负责科目',
            studentClassesToday: '今日课程',
            studentClassesWeek: '本周课程',
            studentAttendance: '出勤率',
            studentSubjects: '已选科目',
            clickToViewGraph: '点击查看图表',
            loadSampleDataTitle: '🚀 开始使用',
            loadSampleDataDesc: '加载示例数据（3个系，10名教师，50名学生，15门课程）以测试系统',
            loadSampleDataBtn: '加载示例数据',
            loadingSample: '加载中...',

            // Tooltips
            mute: '静音',
            unmute: '取消静音',
            voiceOn: '语音控制开启',
            voiceOff: '语音控制关闭',
            handOn: '手势控制开启',
            handOff: '手势控制关闭',

            // Report
            reportTitle: '报告问题 / 反馈',
            reportDesc: '报告错误或发送反馈',
            typeBug: '错误报告',
            typeFeature: '功能请求',
            typeQuestion: '一般问题',
            alertFillRequired: '请填写标题和描述',
            sentSuccess: '报告发送成功！',
            reportId: '报告ID',
            newReport: '发送新报告',
            typeLabel: '类型',
            topicLabel: '主题',
            topicPlaceholder: '简要摘要（例如无法登录）',
            detailLabel: '描述',
            detailPlaceholder: '描述问题或反馈...',
            sendReportBtn: '发送报告',

            // Settings
            settingsTitle: '仪表板设置',
            settingsDesc: '自定义您的仪表板视图',
            resetConfig: '重置所有设置？',
            resetBtn: '重置',
            saved: '已保存！',

            // Shapes
            shapeRounded: '圆角',
            shapePill: '胶囊',
            shapeSharp: '直角',
            shapeSoft: '柔和',
            // Styles
            styleGradient: '渐变',
            styleSolid: '纯色',
            styleGlass: '玻璃',
            styleOutline: '轮廓',
            // Colors
            colorBlue: '蓝色',
            colorEmerald: '祖母绿',
            colorViolet: '紫罗兰',
            colorAmber: '琥珀色',
            colorRose: '玫瑰红',
            colorCyan: '青色',
            colorOrange: '橙色',
            colorPink: '粉色',
            colorRed: '红色',
            colorIndigo: '靛蓝',
            colorTeal: '青色',
            colorLime: '酸橙',
        },
        ja: {
            welcome: "ようこそ",
            systemName: "大学管理システム",
            dashboard: "ダッシュボード",
            schedule: "時間割",
            students: "学生",
            teachers: "教師",
            subjects: "科目",
            rooms: "教室",
            departments: "学部",
            levels: "学年",
            curriculum: "カリキュラム",
            users: "ユーザー",
            logout: "ログアウト",
            save: "保存",
            cancel: "キャンセル",
            all: "すべて",
            filterAll: "すべての{label}",
            confirm: "確認",
            delete: "削除",
            edit: "編集",
            add: "追加",
            search: "検索",
            clear: "クリア",
            clearSelection: "選択をクリア",
            action: "操作",
            // StatCards
            totalStudents: "学生総数",
            totalTeachers: "教師総数",
            totalSubjects: "科目総数",
            totalRooms: "教室総数",
            unitPerson: "人",
            unitSubject: "科目",
            unitRoom: "室",
            statStudents: "学生",
            statTeachers: "教師",
            statUsers: "ユーザー",
            statLevels: "学年",
            statSubjects: "科目",
            statDepartments: "学部",
            statRooms: "教室",
            statCredits: "総単位",
            statCurriculum: "カリキュラム",
            statSchedule: "時間割",
            statScheduledSubjects: "予定科目",
            statHours: "総時間",
            unitTeacher: "人",
            unitLevel: "学年",
            unitDept: "学部",
            unitCredit: "単位",
            unitItem: "項目",
            unitPeriod: "時限",
            unitHour: "時間",
            seq: "番号",
            department: "学科",
            term: "学期",

            // Chat Widget
            chatHeader: "スマートアシスタント (AI)",
            chatWelcome: "こんにちは！AIアシスタントです 🤖\n時間割や大学のデータについて何かお手伝いできますか？",
            chatError: "申し訳ありません、システムエラーです",
            askSchedule: "時間割について聞く...",
            poweredBy: "Powered by Ollama AI (ฟรี)",
            chatProcessError: "処理中にエラーが発生しました",

            // Profile Page
            profileTitle: "プロフィール",
            profileDesc: "アカウントとパスワードの管理",
            changePhoto: "写真を変更",
            newPassword: "新しいパスワード",
            saveChanges: "変更を保存",
            processing: "処理中...",
            fileTooLarge: "ファイルが大きすぎます",
            fileSizeError: "200KB以下の画像を選択してください",
            saveProfileSuccess: "保存しました",
            profileUpdated: "プロフィールを更新しました",
            saveProfileFailed: "保存に失敗しました",
            saveProfileError: "データの保存中にエラーが発生しました",
            // Forms
            editData: "データを編集",
            saveData: "データを保存",
            saving: "保存中...",
            clearForm: "フォームをクリア",
            confirmClear: "全データをクリアしますか?",
            studentId: "学籍番号",
            name: "表示名",
            birthdate: "生年月日",
            deptName: "学部",
            selectDept: "-- 学部を選択 --",
            classLevel: "学年",
            selectLevel: "-- 学年を選択 --",
            password: "パスワード",
            teacherId: "教員番号",
            teacherRoom: "教師室",
            maxHoursLabel: "週最大時間",
            subjectCode: "科目番号",
            subjectName: "科目名",
            credit: "単位",
            theoryHours: "理論時間",
            practiceHours: "実習時間",
            roomName: "教室名/番号",
            roomType: "教室タイプ",
            roomCapacity: "定員",
            usernameLabel: "ユーザー名",
            addUserTitle: "ユーザー管理",

            // TableModal
            manageData: "データベースの {title} データを管理",
            addSubjectBtn: "アイテムを追加",
            templateBtn: "テンプレート",
            importBtn: "Excelをインポート",
            searchPlaceholder: "検索...",
            showing: "{total} 件中 {start} - {end} を表示",
            deleteWarning: "データは完全に削除されます",
            recoverWarning: "データは復元できません",
            templateDownloaded: "テンプレートをダウンロードしました",
            excelEmpty: "Excelファイルが空です",
            foundItems: "{count} 件見つかりました。\nインポートを開始しますか？",
            invalidExcel: "無効なExcelファイル",
            failedDelete: "削除に失敗しました",
            duplicateMsg: "重複データ: \"{value}\"\n上書きしますか？",
            errorMsg: "エラー: {error}",
            noData: "データなし",
            success: "成功",
            warning: "警告",
            all: "すべて",
            filterAll: "すべての{label}",
            theory: "理論",
            practice: "実習",
            subject: "科目",
            teacher: "教師",
            room: "教室",
            type: "タイプ",
            capacity: "定員",
            day: "曜日",
            period: "時限",
            select: "選択",
            autoGenBtn: "自動スケジュール",
            clearTableBtn: "テーブルをクリア",
            printBtn: "印刷",
            deleteSelectedBtn: "選択した項目を削除",
            emptyStateTitle: "スケジュールデータなし",
            emptyStateDesc: "スケジュールを表示するには、学部と学年を選択してください",
            autoGenTitle: "自動スケジュールの確認",
            autoGenMessage: "システムはスケジュールを再生成します。既存のデータが変更される可能性があります。",
            autoGenConfirm: "スケジュール開始",
            autoGenSkipped: "スキップ (データなし)",
            autoGenSuccess: "成功",
            autoGenFail: "失敗",
            manualAddTitle: "科目を追加 (手動)",
            timeDay: "時間 / 曜日",
            monday: "月曜日",
            tuesday: "火曜日",
            wednesday: "水曜日",
            thursday: "木曜日",
            friday: "金曜日",
            saturday: "土曜日",
            sunday: "日曜日",
            lunchBreak: "昼休み",

            // AI Clean Data
            cleanData: "データをクリーンアップ (AI)",
            cleanDataConfirm: "データクリーンアップの確認",
            cleanDataDesc: "AIが名前をフォーマット（プレフィックスを削除）し、スペースを修正します。数秒かかる場合があります。",
            startCleanup: "クリーンアップ開始",
            aiProcessing: "AIがデータをクリーンアップしています...",
            cleanupComplete: "クリーンアップ完了",
            saveChangesQuery: "AIが {count} 件のアイテムをクリーンアップしました。これらの変更をデータベースに保存しますか？",
            reviewOnly: "プレビューのみ",
            noDataToClean: "クリーンアップするデータがありません",

            // DatePicker
            // DatePicker
            dateDay: "日",
            dateMonth: "月",
            dateYear: "年",

            // Placeholders
            namePlaceholder: "例: 山田太郎",
            studentIdPlaceholder: "例: 66302001001",
            passwordPlaceholder: "空白で現在のパスワードを保持",
            teacherIdPlaceholder: "8-10桁の数字",
            teacherRoomPlaceholder: "例: 教員室1",
            subjectCodePlaceholder: "例: 3000-1201",
            subjectNamePlaceholder: "例: 基礎数学",
            roomNamePlaceholder: "例: 3201, PCラボ1",
            deptNamePlaceholder: "例: 情報技術学科",
            usernamePlaceholder: "例: admin01",
            levelNamePlaceholder: "例: 職業1年/1組",

            // Page Titles & Descriptions
            addStudentTitle: "新しい学生を追加",
            addStudentDesc: "システム内の学生データを管理",
            addTeacherTitle: "教師データを追加",
            addTeacherDesc: "システム内の職員データを管理",
            addSubjectTitle: "科目を追加",
            addSubjectDesc: "科目と担当教師を定義",
            addRoomTitle: "教室を追加",
            addRoomDesc: "教室の種類と定員を定義",
            addDeptTitle: "学部を追加",
            addDeptDesc: "学部の追加/削除",
            addLevelTitle: "学年を追加",
            addLevelDesc: "学年の追加/削除",
            addUserDesc: "管理者アカウントの追加/編集/削除",
            scheduleTitle: "スケジュール管理",
            menuNotFound: "メニューが見つかりません",
            pageNotActive: "ページはアクティブではありません",

            // Messages
            saveSuccess: "保存成功",
            updateSuccess: "更新成功",
            duplicateFound: "重複データが見つかりました",
            duplicateConfirm: "上書きしますか？",
            overwrite: "上書き",
            error: "エラー",
            connectionError: "サーバーに接続できません",
            levelSaveSuccess: "学年を追加しました",

            // Curriculum
            curriculumTitle: "カリキュラム設定",
            curriculumDesc: "選択した学年と学部の科目を選択",
            allSubjects: "全ての科目",
            selectSubjectsDesc: "この学年で教える科目を選択",
            askAI: "AIに聞く",
            selectedCount: "選択済み",
            aiRecommended: "AIおすすめ",
            noSubjectsFound: "この学部に科目がありません",
            selectLevelDeptFirst: "開始するには学年と学部を選択してください",
            aiRecommendSuccess: "AIおすすめ成功",
            aiRecommendMessage: "AIが適切な科目を推薦しました",
            aiRecommendError: "現在AIは推薦できません",

            // Schedule extras
            smartAssistant: "スマートアシスタント",
            filterBtn: "フィルター",
            addToTableBtn: "テーブルに追加",
            clearTableTitle: "スケジュールデータをクリア",
            clearMode: "クリアモード",
            clearAll: "全てクリア（全学年）",
            clearCurrent: "現在の学年のみ",
            hours: "時間",
            startTime: "開始時間",
            startPeriod: "開始時限",
            duration: "期間",
            editTitle: "データを編集",

            // TableModal extras
            maxHours: "最大時間",
            username: "ユーザー名",
            fullname: "フルネーム",
            role: "役割",
            studentCount: "学生数",

            // Header
            adminRole: '管理者',
            profile: 'プロフィール',

            // Tooltips
            mute: 'ミュート',
            unmute: 'ミュート解除',
            voiceOn: '音声操作オン',
            voiceOff: '音声操作オフ',
            handOn: 'ハンド操作オン',
            handOff: 'ハンド操作オフ',

            // Report
            reportTitle: '問題報告 / フィードバック',
            reportDesc: 'バグ報告やフィードバックを送信',
            typeBug: 'バグ報告',
            typeFeature: '機能リクエスト',
            typeQuestion: '一般的な質問',
            alertFillRequired: 'タイトルと詳細を入力してください',
            sentSuccess: '報告が送信されました！',
            reportId: '報告ID',
            newReport: '新しい報告を送信',
            typeLabel: 'タイプ',
            topicLabel: 'トピック',
            topicPlaceholder: '短い要約（例：ログインできない）',
            detailLabel: '詳細',
            detailPlaceholder: '問題やフィードバックを説明してください...',
            sendReportBtn: '報告を送信',

            // Settings
            settingsTitle: 'ダッシュボード設定',
            settingsDesc: 'ダッシュボードの表示をカスタマイズ',
            resetConfig: 'すべての設定をリセットしますか？',
            resetBtn: 'リセット',
            saved: '保存しました！',

            // Shapes
            shapeRounded: '丸角',
            shapePill: 'カプセル',
            shapeSharp: '直角',
            shapeSoft: 'ソフト',
            // Styles
            styleGradient: 'グラデーション',
            styleSolid: '単色',
            styleGlass: 'ガラス',
            styleOutline: 'アウトライン',
            // Colors
            colorBlue: '青',
            colorEmerald: 'エメラルド',
            colorViolet: '紫',
            colorAmber: '琥珀',
            colorRose: 'ローズ',
            colorCyan: 'シアン',
            colorOrange: 'オレンジ',
            colorPink: 'ピンク',
            colorRed: '赤',
            colorIndigo: 'インディゴ',
            colorTeal: 'ティール',
            colorLime: 'ライム',

            // Sidebar New Keys
            attendance: '出席',
            aiComparison: 'AI比較',
            issueReports: '問題レポート',
            reportIssue: '問題を報告',
            settings: '設定',
            help: 'ヘルプ',
            viewData: 'データ表示',
            addEdit: '追加/編集',
            importExcel: 'Excelインポート',

            // Dashboard New Keys
            roomUtilization: '教室利用率',
            teachingLoad: '教員負荷',
            teacherDaily: '今日',
            teacherWeekly: '週間',
            teacherTerm: '学期',
            teacherSubjects: '担当科目',
            studentClassesToday: '今日の授業',
            studentClassesWeek: '週間の授業',
            studentAttendance: '出席率',
            studentSubjects: '履修科目',
            clickToViewGraph: 'クリックしてグラフを表示',
            loadSampleDataTitle: '🚀 始める',
            loadSampleDataDesc: 'サンプルデータをロードしてシステムをテスト',
            loadSampleDataBtn: 'サンプルデータをロード',
            loadingSample: 'ロード中...',
            totalHours: "合計時間",
            time: "時間",
            item: "項目",
            agentPlanning: "条件分析中",
            agentReasoning: "戦略設計中",
            agentAction: "スケジュール割当中",
            agentReview: "競合確認中",

            // Login Page
            loginTitle: "ログイン",
            loginSubtitle: "大学管理システム",
            usernameLogin: "ユーザー名",
            passwordLogin: "パスワード",
            loginButton: "ログイン",
            loggingIn: "ログイン中...",
            loginSuccess: "ログイン成功",
            loginWelcome: "システムへようこそ",
            loginFailed: "ログイン失敗",
            loginError: "ユーザー名またはパスワードが無効です",
            tryAgain: "再試行",
            ok: "OK",
            copyright: "© 2025 スパンブリ技術大学",

            // Header
            adminRole: "管理者",
            profile: "プロフィール",
            typeMessage: "メッセージを入力...",

            // Sidebar New Keys
            attendance: '出席',
            aiComparison: 'AI比較',
            issueReports: '問題レポート',
            reportIssue: '問題を報告',
            settings: '設定',
            help: 'ヘルプ',
            viewData: 'データ表示',
            addEdit: '追加/編集',
            importExcel: 'Excelインポート',

            // Dashboard New Keys
            roomUtilization: '教室稼働率',
            teachingLoad: '教育負担',
            teacherDaily: '今日の授業時間',
            teacherWeekly: '今週の授業時間',
            teacherTerm: '学期の授業時間',
            teacherSubjects: '担当科目',
            studentClassesToday: '今日の授業',
            studentClassesWeek: '今週の授業',
            studentAttendance: '出席率',
            studentSubjects: '登録科目',
            clickToViewGraph: 'クリックしてグラフを表示',
            loadSampleDataTitle: '🚀 利用開始',
            loadSampleDataDesc: 'サンプルデータ（3学部、教師10名、学生50名、15科目）を読み込んでシステムをテストします',
            loadSampleDataBtn: 'サンプルデータを読み込む',
            loadingSample: '読み込み中...',
        },
        ko: {
            welcome: "환영합니다",
            systemName: "대학 관리 시스템",
            dashboard: "대시보드",
            schedule: "시간표",
            students: "학생",
            teachers: "교사",
            subjects: "과목",
            rooms: "강의실",
            departments: "학과",
            levels: "학년",
            curriculum: "교육과정",
            users: "사용자",
            logout: "로그아웃",
            save: "저장",
            cancel: "취소",
            confirm: "확인",
            delete: "삭제",
            edit: "편집",
            add: "추가",
            search: "검색",
            clear: "지우기",
            clearSelection: "선택 해제",
            action: "동작",
            // StatCards
            totalStudents: "총 학생 수",
            totalTeachers: "총 교사 수",
            totalSubjects: "총 과목 수",
            totalRooms: "총 강의실 수",
            unitPerson: "명",
            unitSubject: "과목",
            unitRoom: "실",
            statStudents: "학생",
            statTeachers: "교사",
            statUsers: "사용자",
            statLevels: "학년",
            statSubjects: "과목",
            statDepartments: "학과",
            statRooms: "강의실",
            statCredits: "총 학점",
            statCurriculum: "교육과정",
            statSchedule: "시간표",
            statScheduledSubjects: "배정된 과목",
            statHours: "총 시간",
            unitTeacher: "명",
            unitLevel: "학년",
            unitDept: "학과",
            unitCredit: "학점",
            unitItem: "항목",
            unitPeriod: "교시",
            unitHour: "시간",
            seq: "번호",
            department: "학과",
            term: "학기",

            // Chat Widget
            chatHeader: "스마트 어시스턴트 (AI)",
            chatWelcome: "안녕하세요! AI 어시스턴트입니다 🤖\n시간표나 대학 데이터에 대해 도와드릴까요?",
            chatError: "죄송합니다, 시스템 오류입니다",
            askSchedule: "시간표에 대해 질문...",
            poweredBy: "Powered by Ollama AI (ฟรี)",
            chatProcessError: "처리 중 오류 발생",

            // Profile Page
            profileTitle: "프로필",
            profileDesc: "계정 및 비밀번호 관리",
            changePhoto: "사진 변경",
            newPassword: "새 비밀번호",
            saveChanges: "변경 사항 저장",
            processing: "처리 중...",
            fileTooLarge: "파일이 너무 큽니다",
            fileSizeError: "200KB 미만의 이미지를 선택해주세요",
            saveProfileSuccess: "저장 성공",
            profileUpdated: "프로필이 업데이트되었습니다",
            saveProfileFailed: "저장 실패",
            saveProfileError: "데이터 저장 중 오류 발생",
            // Forms
            editData: "데이터 편집",
            saveData: "데이터 저장",
            saving: "저장 중...",
            clearForm: "양식 지우기",
            confirmClear: "모든 데이터를 지우시겠습니까?",
            studentId: "학생 ID",
            name: "표시 이름",
            birthdate: "생년월일",
            deptName: "학과",
            selectDept: "-- 학과 선택 --",
            classLevel: "학년",
            selectLevel: "-- 학년 선택 --",
            password: "비밀번호",
            teacherId: "교사 ID",
            teacherRoom: "교무실",
            maxHoursLabel: "주당 최대 시간",
            subjectCode: "과목 코드",
            subjectName: "과목명",
            credit: "학점",
            theoryHours: "이론 시간",
            practiceHours: "실습 시간",
            roomName: "강의실 명/번호",
            roomType: "강의실 유형",
            roomCapacity: "수용 인원",
            usernameLabel: "사용자 이름",
            addUserTitle: "사용자 관리",

            // TableModal
            manageData: "데이터베이스의 {title} 데이터 관리",
            addSubjectBtn: "항목 추가",
            templateBtn: "템플릿",
            importBtn: "Excel 가져오기",
            searchPlaceholder: "검색...",
            showing: "{total} 중 {start} - {end} 표시",
            deleteWarning: "데이터가 영구적으로 삭제됩니다",
            recoverWarning: "데이터를 복구할 수 없습니다",
            templateDownloaded: "템플릿이 다운로드되었습니다",
            excelEmpty: "Excel 파일이 비어 있습니다",
            foundItems: "{count} 항목을 찾았습니다.\n가져오기를 시작하시겠습니까?",
            invalidExcel: "유효하지 않은 Excel 파일",
            failedDelete: "삭제 실패",
            duplicateMsg: "중복 데이터: \"{value}\"\n덮어쓰시겠습니까?",
            errorMsg: "오류: {error}",
            noData: "데이터 없음",
            success: "성공",
            warning: "경고",
            all: "전체",
            filterAll: "전체 {label}",
            theory: "이론",
            practice: "실습",
            subject: "과목",
            teacher: "교사",
            room: "강의실",
            type: "유형",
            capacity: "수용 인원",
            day: "요일",
            period: "교시",
            select: "선택",
            autoGenBtn: "자동 시간표",
            clearTableBtn: "시간표 지우기",
            printBtn: "인쇄",
            deleteSelectedBtn: "선택 삭제",
            emptyStateTitle: "시간표 데이터 없음",
            emptyStateDesc: "시간표를 보려면 학과와 학년을 선택하세요",
            autoGenTitle: "자동 시간표 확인",
            autoGenMessage: "시스템이 시간표를 재생성합니다. 기존 데이터가 변경될 수 있습니다.",
            autoGenConfirm: "시간표 생성 시작",
            autoGenSkipped: "건너뜀 (데이터 없음)",
            autoGenSuccess: "성공",
            autoGenFail: "실패",
            manualAddTitle: "과목 추가 (수동)",
            timeDay: "시간 / 요일",
            monday: "월요일",
            tuesday: "화요일",
            wednesday: "수요일",
            thursday: "목요일",
            friday: "금요일",
            saturday: "토요일",
            sunday: "일요일",
            lunchBreak: "점심 시간",

            // AI Clean Data
            cleanData: "데이터 정리 (AI)",
            cleanDataConfirm: "데이터 정리 확인",
            cleanDataDesc: "AI가 이름 형식을 지정(접두사 제거)하고 간격을 수정합니다. 몇 초 정도 걸릴 수 있습니다.",
            startCleanup: "정리 시작",
            aiProcessing: "AI가 데이터를 정리하고 있습니다...",
            cleanupComplete: "정리 완료",
            saveChangesQuery: "AI가 {count} 항목을 정리했습니다. 이 변경 사항을 데이터베이스에 저장하시겠습니까?",
            reviewOnly: "미리보기만",
            noDataToClean: "정리할 데이터가 없습니다",

            // DatePicker
            // DatePicker
            dateDay: "일",
            dateMonth: "월",
            dateYear: "년",

            // Placeholders
            namePlaceholder: "예: 홍길동",
            studentIdPlaceholder: "예: 66302001001",
            passwordPlaceholder: "빈칸으로 두면 현재 비밀번호 유지",
            teacherIdPlaceholder: "8-10자리 숫자",
            teacherRoomPlaceholder: "예: 교무실 1",
            subjectCodePlaceholder: "예: 3000-1201",
            subjectNamePlaceholder: "예: 기초 수학",
            roomNamePlaceholder: "예: 3201, 컴퓨터실 1",
            deptNamePlaceholder: "예: 정보기술학과",
            usernamePlaceholder: "예: admin01",
            levelNamePlaceholder: "예: 직업 1학년/1반",

            // Page Titles & Descriptions
            addStudentTitle: "새 학생 추가",
            addStudentDesc: "시스템의 학생 데이터 관리",
            addTeacherTitle: "교사 데이터 추가",
            addTeacherDesc: "시스템의 교직원 데이터 관리",
            addSubjectTitle: "과목 추가",
            addSubjectDesc: "과목 및 담당 교사 정의",
            addRoomTitle: "강의실 추가",
            addRoomDesc: "강의실 유형 및 수용 인원 정의",
            addDeptTitle: "학과 추가",
            addDeptDesc: "학과 추가/삭제",
            addLevelTitle: "학년 추가",
            addLevelDesc: "학년 추가/삭제",
            addUserDesc: "관리자 계정 추가/편집/삭제",
            scheduleTitle: "시간표 관리",
            menuNotFound: "메뉴를 찾을 수 없음",
            pageNotActive: "페이지가 활성화되지 않음",

            // Messages
            saveSuccess: "저장 성공",
            updateSuccess: "업데이트 성공",
            duplicateFound: "중복 데이터 발견",
            duplicateConfirm: "덮어쓰시겠습니까?",
            overwrite: "덮어쓰기",
            error: "오류",
            connectionError: "서버에 연결할 수 없음",
            levelSaveSuccess: "학년이 추가되었습니다",

            // Curriculum
            curriculumTitle: "교육과정 설정",
            curriculumDesc: "선택한 학년 및 학과의 과목 선택",
            allSubjects: "모든 과목",
            selectSubjectsDesc: "이 학년에서 가르칠 과목 선택",
            askAI: "AI에게 묻기",
            selectedCount: "선택됨",
            aiRecommended: "AI 추천",
            noSubjectsFound: "이 학과에 과목이 없습니다",
            selectLevelDeptFirst: "시작하려면 학년과 학과를 선택하세요",
            aiRecommendSuccess: "AI 추천 성공",
            aiRecommendMessage: "AI가 적합한 과목을 추천했습니다",
            aiRecommendError: "현재 AI가 추천할 수 없습니다",

            // Schedule extras
            smartAssistant: "스마트 어시스턴트",
            filterBtn: "필터",
            addToTableBtn: "시간표에 추가",
            clearTableTitle: "시간표 데이터 지우기",
            clearMode: "지우기 모드",
            clearAll: "전체 지우기 (모든 학년)",
            clearCurrent: "현재 학년만",
            hours: "시간",
            startTime: "시작 시간",
            startPeriod: "시작 교시",
            duration: "기간",
            editTitle: "데이터 편집",

            // TableModal extras
            maxHours: "최대 시간",
            username: "사용자 이름",
            fullname: "전체 이름",
            role: "역할",
            studentCount: "학생 수",
            totalHours: "총 시간",
            time: "시간",
            item: "항목",
            agentPlanning: "조건 분석 중",
            agentReasoning: "전략 설계 중",
            agentAction: "시간표 배정 중",
            agentReview: "충돌 확인 중",

            // Login Page
            loginTitle: "로그인",
            loginSubtitle: "대학 관리 시스템",
            usernameLogin: "사용자 이름",
            passwordLogin: "비밀번호",
            loginButton: "로그인",
            loggingIn: "로그인 중...",
            loginSuccess: "로그인 성공",
            loginWelcome: "시스템에 오신 것을 환영합니다",
            loginFailed: "로그인 실패",
            loginError: "사용자 이름 또는 비밀번호가 잘못되었습니다",
            tryAgain: "다시 시도",
            ok: "확인",
            copyright: "© 2025 수판부리 기술대학",

            // Header
            adminRole: "관리자",
            profile: "프로필",
            typeMessage: "메시지 입력...",

            // Tooltips
            mute: '음소거',
            unmute: '음소거 해제',
            voiceOn: '음성 제어 켜기',
            voiceOff: '음성 제어 끄기',
            handOn: '손 제어 켜기',
            handOff: '손 제어 끄기',

            // Report
            reportTitle: '문제 신고 / 피드백',
            reportDesc: '버그 신고 또는 피드백 보내기',
            typeBug: '버그 신고',
            typeFeature: '기능 요청',
            typeQuestion: '일반 질문',
            alertFillRequired: '제목과 내용을 입력해주세요',
            sentSuccess: '신고가 성공적으로 전송되었습니다!',
            reportId: '신고 ID',
            newReport: '새 신고 보내기',
            typeLabel: '유형',
            topicLabel: '주제',
            topicPlaceholder: '간단한 요약 (예: 로그인 불가)',
            detailLabel: '내용',
            detailPlaceholder: '문제 또는 피드백을 설명해주세요...',
            sendReportBtn: '신고 보내기',

            // Settings
            settingsTitle: '대시보드 설정',
            settingsDesc: '대시보드 화면 사용자 정의',
            resetConfig: '모든 설정을 초기화하시겠습니까?',
            resetBtn: '초기화',
            saved: '저장됨!',

            // Shapes
            shapeRounded: '둥근 모서리',
            shapePill: '캡슐',
            shapeSharp: '직각',
            shapeSoft: '부드러운',
            // Styles
            styleGradient: '그라데이션',
            styleSolid: '단색',
            styleGlass: '유리',
            styleOutline: '외곽선',
            // Colors
            colorBlue: '파랑',
            colorEmerald: '에메랄드',
            colorViolet: '보라',
            colorAmber: '호박색',
            colorRose: '장미',
            colorCyan: '청록',
            colorOrange: '주황',
            colorPink: '분홍',
            colorRed: '빨강',
            colorIndigo: '남색',
            colorTeal: '청록',
            colorLime: '라임',

            // Sidebar New Keys
            attendance: '출석',
            schedule: '시간표',
            aiComparison: 'AI 비교',
            issueReports: '문제 보고서',
            reportIssue: '문제 신고',
            settings: '설정',
            help: '도움말',
            viewData: '데이터 보기',
            addEdit: '추가/편집',
            importExcel: 'Excel 가져오기',

            // Dashboard New Keys
            roomUtilization: '강의실 사용률',
            teachingLoad: '수업 부담',
            teacherDaily: '오늘 수업',
            teacherWeekly: '주간 수업',
            teacherTerm: '학기 수업',
            teacherSubjects: '담당 과목',
            studentClassesToday: '오늘의 수업',
            studentClassesWeek: '주간 수업',
            studentAttendance: '출석률',
            studentSubjects: '수강 과목',
            clickToViewGraph: '그래프 보기',
            loadSampleDataTitle: '🚀 시작하기',
            loadSampleDataDesc: '샘플 데이터를 로드하여 시스템 테스트',
            loadSampleDataBtn: '샘플 데이터 로드',
            loadingSample: '로딩 중...',
        }
    };

    const t = (key) => {
        const langObj = translations[language] ? translations[language] : translations['en'];
        return langObj[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
